import type {
  HrAttendanceRecord,
  HrDocument,
  HrEmployee,
  HrLeaveRequest,
  HrOnboardingCase,
} from './types';

export const INITIAL_EMPLOYEES: HrEmployee[] = [
  {
    id: 'emp-001',
    staffNumber: 'KCU-STF-1042',
    firstName: 'Sarah',
    lastName: 'Nambi',
    email: 's.nambi@kcu.ac.ug',
    phone: '+256 700 112233',
    department: 'Registry',
    school: 'Central Administration',
    jobTitle: 'Senior Registry Officer',
    category: 'Administrative',
    employmentType: 'Full-time',
    status: 'Active',
    hireDate: '2019-03-15',
    managerName: 'Dr. Peter Muwonge',
    leaveBalanceDays: 18,
    hasUserAccount: true,
  },
  {
    id: 'emp-002',
    staffNumber: 'KCU-STF-1088',
    firstName: 'David',
    lastName: 'Kato',
    email: 'd.kato@kcu.ac.ug',
    phone: '+256 701 445566',
    department: 'Finance',
    school: 'Central Administration',
    jobTitle: 'Accounts Assistant',
    category: 'Administrative',
    employmentType: 'Full-time',
    status: 'On Leave',
    hireDate: '2021-08-01',
    managerName: 'Ms. Ruth Akello',
    leaveBalanceDays: 6,
    hasUserAccount: true,
  },
  {
    id: 'emp-003',
    staffNumber: 'KCU-LEC-0214',
    firstName: 'James',
    lastName: 'Okello',
    email: 'lecturer.appraisal@kcu.ac.ug',
    phone: '+256 702 778899',
    department: 'Nursing & Midwifery',
    school: 'School of Health Sciences',
    jobTitle: 'Senior Lecturer',
    category: 'Academic',
    employmentType: 'Full-time',
    status: 'Active',
    hireDate: '2016-01-10',
    managerName: 'Prof. Mary Achieng',
    leaveBalanceDays: 12,
    hasUserAccount: true,
  },
  {
    id: 'emp-004',
    staffNumber: 'KCU-STF-1135',
    firstName: 'Faith',
    lastName: 'Tumusiime',
    email: 'f.tumusiime@kcu.ac.ug',
    phone: '+256 703 990011',
    department: 'Human Resources',
    school: 'Central Administration',
    jobTitle: 'HR Assistant',
    category: 'Administrative',
    employmentType: 'Full-time',
    status: 'Probation',
    hireDate: '2025-11-01',
    managerName: 'Grace Nakato',
    leaveBalanceDays: 21,
    hasUserAccount: true,
  },
  {
    id: 'emp-005',
    staffNumber: 'KCU-STF-0998',
    firstName: 'Robert',
    lastName: 'Ssebunya',
    email: 'r.ssebunya@kcu.ac.ug',
    phone: '+256 704 223344',
    department: 'ICT',
    school: 'Central Administration',
    jobTitle: 'Systems Administrator',
    category: 'Support',
    employmentType: 'Contract',
    status: 'Active',
    hireDate: '2023-06-20',
    managerName: 'Mr. Henry Lubega',
    leaveBalanceDays: 14,
    hasUserAccount: true,
  },
  {
    id: 'emp-006',
    staffNumber: 'KCU-LEC-0188',
    firstName: 'Agnes',
    lastName: 'Nalwoga',
    email: 'a.nalwoga@kcu.ac.ug',
    phone: '+256 705 556677',
    department: 'Public Health',
    school: 'School of Health Sciences',
    jobTitle: 'Lecturer',
    category: 'Academic',
    employmentType: 'Full-time',
    status: 'Active',
    hireDate: '2018-09-03',
    managerName: 'Dr. Samuel Wasswa',
    leaveBalanceDays: 9,
    hasUserAccount: true,
  },
];

export const INITIAL_LEAVE_REQUESTS: HrLeaveRequest[] = [
  {
    id: 'lv-001',
    employeeId: 'emp-002',
    employeeName: 'David Kato',
    department: 'Finance',
    leaveType: 'Annual',
    startDate: '2026-06-02',
    endDate: '2026-06-13',
    days: 10,
    reason: 'Family travel',
    status: 'Approved',
    submittedAt: '2026-05-10T09:00:00Z',
    reviewedBy: 'Grace Nakato',
    reviewedAt: '2026-05-11T14:30:00Z',
  },
  {
    id: 'lv-002',
    employeeId: 'emp-001',
    employeeName: 'Sarah Nambi',
    department: 'Registry',
    leaveType: 'Sick',
    startDate: '2026-06-09',
    endDate: '2026-06-10',
    days: 2,
    reason: 'Medical appointment',
    status: 'Pending',
    submittedAt: '2026-06-08T07:45:00Z',
  },
  {
    id: 'lv-003',
    employeeId: 'emp-005',
    employeeName: 'Robert Ssebunya',
    department: 'ICT',
    leaveType: 'Study',
    startDate: '2026-07-01',
    endDate: '2026-07-15',
    days: 11,
    reason: 'Professional certification course',
    status: 'Pending',
    submittedAt: '2026-06-01T11:20:00Z',
  },
  {
    id: 'lv-004',
    employeeId: 'emp-006',
    employeeName: 'Agnes Nalwoga',
    department: 'Public Health',
    leaveType: 'Maternity',
    startDate: '2026-08-01',
    endDate: '2026-11-30',
    days: 90,
    reason: 'Maternity leave',
    status: 'Pending',
    submittedAt: '2026-05-28T16:00:00Z',
  },
];

export const INITIAL_ATTENDANCE: HrAttendanceRecord[] = [
  {
    id: 'att-001',
    employeeId: 'emp-001',
    employeeName: 'Sarah Nambi',
    department: 'Registry',
    date: '2026-06-05',
    checkIn: '07:58',
    checkOut: '17:05',
    hours: 9.1,
    status: 'Present',
  },
  {
    id: 'att-002',
    employeeId: 'emp-004',
    employeeName: 'Faith Tumusiime',
    department: 'Human Resources',
    date: '2026-06-05',
    checkIn: '08:22',
    checkOut: '17:30',
    hours: 9.1,
    status: 'Late',
  },
  {
    id: 'att-003',
    employeeId: 'emp-005',
    employeeName: 'Robert Ssebunya',
    department: 'ICT',
    date: '2026-06-05',
    checkIn: '08:01',
    checkOut: '17:15',
    hours: 9.2,
    status: 'Present',
  },
  {
    id: 'att-004',
    employeeId: 'emp-002',
    employeeName: 'David Kato',
    department: 'Finance',
    date: '2026-06-05',
    checkIn: 'â€”',
    checkOut: null,
    hours: 0,
    status: 'On Leave',
  },
];

export const INITIAL_ONBOARDING: HrOnboardingCase[] = [
  {
    id: 'onb-001',
    employeeName: 'Faith Tumusiime',
    jobTitle: 'HR Assistant',
    department: 'Human Resources',
    startDate: '2025-11-01',
    progress: 75,
    tasks: [
      { id: 't1', label: 'Issue staff ID', status: 'Done', owner: 'HR' },
      { id: 't2', label: 'Create user account', status: 'Done', owner: 'ICT' },
      { id: 't3', label: 'Sign appointment letter', status: 'Done', owner: 'Employee' },
      { id: 't4', label: 'Orientation â€” university policies', status: 'In Progress', owner: 'HR' },
      { id: 't5', label: 'Department induction', status: 'Pending', owner: 'HOD' },
    ],
  },
  {
    id: 'onb-002',
    employeeName: 'Joel Musinguzi',
    jobTitle: 'Library Assistant',
    department: 'Library',
    startDate: '2026-06-16',
    progress: 20,
    tasks: [
      { id: 't1', label: 'Pre-employment documents verified', status: 'Done', owner: 'HR' },
      { id: 't2', label: 'Create user account', status: 'Pending', owner: 'ICT' },
      { id: 't3', label: 'Issue staff ID', status: 'Pending', owner: 'HR' },
      { id: 't4', label: 'Orientation schedule sent', status: 'Pending', owner: 'HR' },
    ],
  },
];

export const INITIAL_DOCUMENTS: HrDocument[] = [
  {
    id: 'doc-001',
    employeeId: 'emp-003',
    employeeName: 'Dr. James Okello',
    title: 'Appointment Letter â€” Senior Lecturer',
    category: 'Appointment Letter',
    uploadedAt: '2024-01-15',
    expiresAt: null,
    fileName: 'appointment-okello-2024.pdf',
  },
  {
    id: 'doc-002',
    employeeId: 'emp-001',
    employeeName: 'Sarah Nambi',
    title: 'Employment Contract 2023â€“2026',
    category: 'Contract',
    uploadedAt: '2023-01-10',
    expiresAt: '2026-12-31',
    fileName: 'contract-nambi-2023.pdf',
  },
  {
    id: 'doc-003',
    employeeId: 'emp-005',
    employeeName: 'Robert Ssebunya',
    title: 'ICT Systems Access Policy â€” Signed',
    category: 'Policy Acknowledgement',
    uploadedAt: '2023-06-25',
    expiresAt: null,
    fileName: 'policy-ict-ssebunya.pdf',
  },
  {
    id: 'doc-004',
    employeeId: 'emp-004',
    employeeName: 'Faith Tumusiime',
    title: 'Probation Appointment Letter',
    category: 'Appointment Letter',
    uploadedAt: '2025-10-28',
    expiresAt: '2026-04-30',
    fileName: 'probation-tumusiime.pdf',
  },
];
